### ISSUE TITLE
in the NusicPlayer.java is 3 errors 

### ISSUE THREAD

**Issue by Dirkstaal** [edgardavtyan/material-player#2]
.getQueueIndex
.getPath
and .getTrackTitle ?

**Comment by Dirkstaal** [comment]
MusicPlayer.java sorry

**Comment by Dirkstaal** [comment]
MusicPlayer.java sorry

**Comment by Dirkstaal** [comment]
Solved by creating a getter for each of the errors.

**Comment by Dirkstaal** [comment]
it did not solve it.

**Comment by edgardavtyan** [comment]
Look at Issue #5
